version: "3"
services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "8886:8886"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongodb/blog
    command: ["npm", "run", "prod"]
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: on-failure
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
